### ISSUE TITLE
Some board members are listed under Leadership & Staff on profile pages

### ISSUE THREAD

**Issue by lovemedicine** [public-accountability/littlesis-rails#1680] opened 2024-04-26 00:10 UTC
For example, all of these are board relationships and none of them are executive or employee relationships:

<img width="603" alt="Screen Shot 2024-04-25 at 8 08 10 PM" src="https://github.com/public-accountability/littlesis-rails/assets/61064705/88e046cb-e03a-4cfe-b64d-11cd2d3c9509">

**Comment by jessib** [comment] 2024-04-26 00:46
I'd be happy to try to work on this.

**Comment by aepyornis** [comment] 2024-04-26 22:04
So I solved the issue, although there is probably a bug somewhere.

Some background:  There are 12 categories of relationships. Some categories, like Position, have extra attributes stored on connected models. It is on the position model where `is_board` is set. We also use an another model, `Link`, to do more performant and easier querying of relationships. The links table should be kept in-sync with relationships. Here is where what determines the subcategory for the profile page: https://github.com/public-accountability/littlesis-rails/blob/main/app/models/link/subcategory.rb

[This callback in Position](https://github.com/public-accountability/littlesis-rails/blob/main/app/models/position.rb#L8) should trigger a recacluation of those categories when is_board is updated, but that didn't happen. I don't know if that is no longer working as intended or if the problem is elsewhere.

I fixed the page by running this in the console:

`Entity.find(444743).links.each(&:recalculate_subcategory)`

**Comment by lovemedicine** [comment] 2024-04-26 22:14
FYI I noticed the same problem for other entities I was adding board relationships to yesterday, eg:
https://littlesis.org/org/444715-Downtown_Asheville_BID
https://littlesis.org/entities/315738-Asheville_Area_Chamber_of_Commerce

**Comment by jessib** [comment] 2024-04-26 23:02
> 
> [This callback in Position](https://github.com/public-accountability/littlesis-rails/blob/main/app/models/position.rb#L8) should trigger a recacluation of those categories when is_board is updated, but that didn't happen. I don't know if that is no longer working as intended or if the problem is elsewhere.
> 

An `after_update` callback would only run on an update, so maybe this should be an an `after_save` so it runs on create as well?

**Comment by aepyornis** [comment] 2024-04-27 15:41
@jessib I added a failing test that demonstrates the issue: https://github.com/public-accountability/littlesis-rails/pull/1685 

That could be it. Let's try after_save. Also, the update to position is using [accepts_nested_attributes_for](https://github.com/public-accountability/littlesis-rails/blob/main/app/models/relationship.rb#L74), so let's research which callbacks those enable. It's possible that the [ActiveRecord::AttributeMethods::Dirty](https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Dirty.html) isn't activated in this case? Maybe we should remove `if: saved_change_to_is_board?`, since there's really no harm in updating that for other updates to position.

**Comment by jessib** [comment] 2024-04-29 01:49
I'm a bit confused, but the `after_update` wasn't seeming to be called even on update, but works fine (including the dirty records check) with `after_save`. 
PR #1687 won't help the existing links that are incorrect (those will need `recalculate_subcategory` called on them), but should fix going forward.

**Comment by josephlacey** [comment] 2024-05-14 14:19
@lovemedicine This should be fixed with @jessib's PR.  I'm going to close this issue as fixed, but report back if you find otherwise.

**Closed by josephlacey** 2024-05-14 14:19 UTC
