### ISSUE TITLE
Page is cropped on entity page

### ISSUE THREAD

**Issue by betsydupuis** [public-accountability/littlesis-rails#1701] opened 2024-07-11 15:40 UTC
Browser: OSX, Chrome

Occasionally when clicking entity with a large number of relationships, the overflow of the page is cropped. Issue resolves sometimes by refreshing page but not always. Goes away when inspecting, so difficult to diagnose. 

<img width="1211" alt="Screenshot 2024-07-11 at 10 35 59 AM" src="https://github.com/public-accountability/littlesis-rails/assets/2096627/0c4cd432-f7ab-4ce4-a968-1756f10db51f">

**Comment by josephlacey** [comment] 2024-07-12 19:45
@betsydupuis I'm able to replicate this on the live site with a 1680x1050 screen.  On a larger screen (2240x1400), I see the same white space but just not as large.   It looks like adding a simple `overflow: hidden` to the `body` tag will fix the issue, but I'm not able to replicate this locally which is odd.

**Comment by betsydupuis** [comment] 2024-07-13 01:55
I think it's the html height, but not sure.

I'll keep an eye out for it.

**Comment by betsydupuis** [comment] 2024-07-16 22:41
I haven't seen anything today. If the build is up to date, then I think it's safe to close this.

**Comment by josephlacey** [comment] 2024-07-16 23:51
This PR fixes the white space but there's a regression.  The title of the page renders behind the header.  Need to replicate the locally.

**Comment by betsydupuis** [comment] 2024-07-17 00:25
Probably need to sort the positioning order

Betsy Dupuis
She / Her

**Comment by josephlacey** [comment] 2024-07-24 21:11
> This PR fixes the white space but there's a regression. The title of the page renders behind the header. Need to replicate this locally.

After more testing, I can't replicate this regression.  This commit is live and the extra whitespace is fixed based on my testing.  @betsydupuis can you confirm?

**Comment by josephlacey** [comment] 2024-11-12 23:18
This should be fixed.

**Closed by josephlacey** 2024-11-12 23:18 UTC
Labels: bug, profile page, ready
