### ISSUE TITLE
Board member showing up under "business positions" list rather than "board members"

### ISSUE THREAD

**Issue by betsydupuis** [public-accountability/littlesis-rails#1746] opened 2024-10-07 17:32 UTC
It's on this [entity](https://littlesis.org/entities/42745-Antonio_Gracias) that I noticed it. 

The relationship is set to board member

**Comment by josephlacey** [comment] 2024-10-14 16:21
Closing this a duplicate of the #1747

**Closed by josephlacey** 2024-10-14 16:21 UTC
